version: "3"
services:
  arm64v8-standalone-builder:
    container_name: arm64v8-standalone-builder
    build:
      context: ./images/arm64v8
      dockerfile: Dockerfile
    volumes:
      - ./sources:/sources