version: "3"
services:
  standalone-builder:
    container_name: standalone-builder
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./sources:/sources
      - ./cross-compilers:/cross-compilers