FROM alpine:3.15

RUN apk add --no-cache patch binutils xz musl-dev python3 python3-dev jq make linux-headers cmake perl git tar gzip pkgconfig py3-pip gcc g++ libtool automake autoconf gcc

CMD [ "/bin/sh" ]